{
 "title": "Full dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2m",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temperature\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  humidity\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "gauge",
   "description": "2.5 um particles",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  u25\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "PM 10",
   "type": "gauge",
   "description": "10 um particles",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  u10\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Temperature History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  temperature\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Humidity History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "Humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  humidity\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Particle Concentration History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "conμgm3", "label": "Concentration" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  u25,\n  u10\nFROM airquality\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  }
 ]
}